const { chromium } = require('playwright');
const assert = require('node:assert/strict');
require('node:fs').mkdirSync('artifacts', {recursive:true});
(async () => {
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8080/');
 await page.evaluate(()=>localStorage.setItem('elan:v1:settings',JSON.stringify({precountSec:0,sound:false,voice:false})));
 await page.reload();await page.screenshot({path:'artifacts/elan-home.png',fullPage:true});
 assert.equal(await page.locator('[data-mode]').count(),5);
 await page.locator('#nav-timers').click();assert.equal(await page.locator('#nav-timers').getAttribute('aria-current'),'location');
 await page.locator('#nav-settings').click();await page.locator('#settings').waitFor({state:'visible'});await page.screenshot({path:'artifacts/elan-settings.png',fullPage:true});await page.locator('#settings-close').click();
 await page.locator('#nav-home').click();assert.equal(await page.locator('#nav-home').getAttribute('aria-current'),'page');
 await page.locator('input[name=min]').fill('0');await page.locator('input[name=sec]').fill('2');await page.locator('#start').click();
 assert.ok(await page.locator('#bottom-nav').isHidden());
 await page.locator('#summary').waitFor({state:'visible'}); await page.screenshot({path:'artifacts/elan-summary.png',fullPage:true}); assert.match(await page.locator('#summary-message').innerText(),/terminée/);
 await page.locator('#home-button').click();await page.locator('[data-mode=chrono]').click();await page.locator('#start').click();
 await page.waitForTimeout(250);await page.locator('#lap').click();await page.waitForTimeout(200);await page.locator('#lap').click();
 assert.equal(await page.locator('#laps li').count(),2);await page.locator('#pause').click();const time=await page.locator('#clock').innerText();
 await page.waitForTimeout(1100);assert.equal(await page.locator('#clock').innerText(),time);await page.locator('#pause').click();await page.locator('#stop').click();
 assert.equal(await page.locator('#summary-laps li').count(),2);
 await page.locator('#home-button').click();await page.locator('[data-mode=amrap]').click();await page.locator('#start').click();
 await page.locator('#plus').click();await page.locator('#plus').click();await page.locator('#minus').click();assert.equal(await page.locator('#rep-count').innerText(),'1');
 await page.screenshot({path:'artifacts/elan-session.png',fullPage:true});
 await page.locator('#pause').click();await page.reload();await page.locator('#recover').click();assert.equal(await page.locator('#rep-count').innerText(),'1');assert.equal(await page.locator('#pause').innerText(),'Reprendre');
 await page.locator('#stop').click();await page.locator('#stop-confirm').click();assert.match(await page.locator('#summary-message').innerText(),/interrompue/);
 await page.locator('#home-button').click();await page.locator('[data-mode=intervals]').click();await page.locator('input[name=workSec]').fill('1');await page.locator('input[name=restSec]').fill('1');await page.locator('input[name=rounds]').fill('2');await page.locator('#start').click();
 await page.waitForTimeout(1200);assert.equal(await page.locator('#session-title').innerText(),'Repos');await page.locator('#summary').waitFor({state:'visible'});
 await page.locator('#home-button').click();await page.locator('[data-mode=emom]').click();await page.locator('input[name=minutes]').fill('1');await page.locator('#start').click();assert.equal(await page.locator('#round-label').innerText(),'1 / 1');
 await page.locator('#stop').click();await page.locator('#stop-confirm').click();await page.locator('#home-button').click();
 await page.locator('#settings-open').click();await page.locator('select[name=precountSec]').selectOption('3');await page.locator('#settings-form button[type=submit]').click();
 await page.locator('[data-mode=amrap]').click();await page.locator('#start').click();assert.equal(await page.locator('#session-title').innerText(),'Prépare-toi');assert.ok(await page.locator('#rep-panel').isHidden());
 await page.waitForTimeout(3200);assert.ok(await page.locator('#rep-panel').isVisible());
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
 await page.locator('#stop').click();await page.locator('#stop-confirm').click();await page.locator('#home-button').click();
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'artifacts/elan-desktop.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:320,height:740});await page.locator('#nav-home').click();await page.screenshot({path:'artifacts/elan-small.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: five modes, laps, pauses, reps, reload recovery, early stop, interval boundaries, precount, mobile/desktop overflow, no JS errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
